name: Deploy Production

on:
  push:
    branches:
      - main  # Triggers when you push to your main branch

permissions:
  contents: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages Root
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: /   # Deploys directly to the root url
          clean: true        # Deletes old production files, but leaves target-folders safe
